[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "itc_fit"
version = "0.1.0"
description = "A custom fork optimized for notebooks"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "tqdm"
]

[tool.setuptools]
# Tells setuptools to automatically discover your package directories
package-dir = { "" = "src" }
packages = { find = { where = ["src"] } }
